version: "3.7"
services:
  vue:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports: 
      - 8080:8080
      - 3000:3000
    tty: true
volumes:
  node_modules:
      driver: local